Update mountOssfs

diff --git a/linux/mountOssfs b/linux/mountOssfs
--- a/linux/mountOssfs
+++ b/linux/mountOssfs
@@ -15,10 +15,15 @@ arr_bucket=(djangotest jiangkehot univerdream-aliyun-bill univerdream-bj-registr
 ossfs_point=/data/ossfs
 
 # config
-[ -f ~/.ssh/AccessKey ] && source ~/.ssh/AccessKey
+exiterr()  { echo "Error: $1" >&2; exit 1; }
+# mount脚本依赖/root/.ssh/AccessKey
+if [ ! -f /root/.ssh/AccessKey ]; then
+	exiterr "/root/.ssh/AccessKey不存在，此脚本依赖文件/root/.ssh/AccessKey"
+fi
+source ~/.ssh/AccessKey
 touch /etc/passwd-ossfs
 for dir in ${arr_bucket[@]} ;do
-    if ! grep "$dir" /etc/passwd-ossfs; then
+    if ! grep -q "$dir" /etc/passwd-ossfs; then
     	echo $dir:$AccessKeyID:$AccessKeySecret >> /etc/passwd-ossfs
     fi
 done
@@ -35,7 +40,7 @@ done
 chmod +x /etc/rc.d/rc.local
 echo 'sleep 5' >> /etc/rc.local
 for dir in ${arr_bucket[@]} ;do
-  if ! grep '$dir' /etc/rc.d/rc.local; then
+  if ! grep -q "$dir" /etc/rc.d/rc.local; then
       echo "ossfs $dir ${ossfs_point}/${dir} -ourl=http://oss-cn-beijing-internal.aliyuncs.com" >> /etc/rc.local
   fi
 done
